# Notes:
# - Docker containers with R, etc. provided by rocker.  See <https://hub.docker.com/r/rocker/verse>.
# - Builds attempted for 3.6.3, 4.0.5, and the *latest* R edition supported by rocker.

version: 2.1
jobs:
  Build-for-r4_0_5:
    docker:
      - image: rocker/verse:4.0.5
    resource_class: medium

    steps:
      - checkout
      - run:
          name: Review checkout
          command: ls -la

      - run:
          name: Install Linux dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -yq texlive-fonts-recommended
            sudo apt-get install -yq texlive-fonts-extra
      - run:
          name: Install R dependencies
          command: |
            R -e 'install.packages("BiocManager")'
            R -e 'BiocManager::install(c("GenomicRanges", "edgeR", "biomaRt"))'
            R -e 'install.packages("covr")'
            R -e 'install.packages("conflicted")'
      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'sessionInfo()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: |
            # Install suggested packages
            R -e 'install.packages("png")'
            # Perform package check
            R CMD check *tar.gz
      - run:
          name: Check coverage
          command: Rscript -e 'library(covr); codecov(quiet = FALSE)'

  Build-for-rLATEST:
    docker:
      - image: rocker/verse:latest
    resource_class: medium

    steps:
      - checkout
      - run:
          name: Review checkout
          command: ls -la

      - run:
          name: Install Linux dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -yq texlive-fonts-recommended
            sudo apt-get install -yq texlive-fonts-extra
      - run:
          name: Install R dependencies
          command: |
            R -e 'install.packages("BiocManager")'
            R -e 'BiocManager::install(c("GenomicRanges", "edgeR", "biomaRt"))'
            R -e 'install.packages("covr")'
            R -e 'install.packages("conflicted")'
      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'sessionInfo()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: |
            # Install suggested packages
            R -e 'install.packages("png")'
            # Perform package check
            R CMD check *tar.gz
      - run:
          name: Check coverage
          command: Rscript -e 'library(covr); codecov(quiet = FALSE)'

workflows:
  version: 2
  Prepare-All-R-Editions:
    jobs:
      - Build-for-r4_0_5
      - Build-for-rLATEST
